name: Frontend CI with Validation and Docker Build #pull

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install validation tools
        run: |
          npm install -g htmlhint csslint eslint

      - name: Run HTMLHint
        run: |
          htmlhint "**/*.html"

      - name: Run CSSLint
        run: |
          csslint "**/*.css" || echo "CSSLint issues found"

      - name: Run ESLint
        run: |
          eslint "**/*.js" || echo "ESLint issues found"

  build-and-push:
    needs: validate-frontend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ibd-frontend:latest -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push dannynsengimana97/ibd-frontend:latest
